#! /usr/bin/env python3

import sys

from mccommands import *

commands = [
'/difficulty normal',
'/gamerule naturalRegeneration false',
'/time set day',
'/weather clear 1000000',
'/worldborder set 2000',
'/gamerule commandBlockOutput false',
'/setworldspawn 0 255 0',
'/fill -15 253 -15 15 255 15 minecraft:barrier 0 hollow',
'/fill -14 255 -14 14 255 14 minecraft:air',
'/scoreboard objectives add Health health',
'/scoreboard objectives setdisplay list Health',
'/scoreboard objectives add KILLS playerKillCount',
'/scoreboard objectives add DEATHS deathCount',
'/fill 0 0 0 9 7 16 minecraft:bedrock 0 hollow',
'/setblock 0 2 5 minecraft:redstone_block',
'/fill 3 1 1 3 1 15 minecraft:redstone_wire',
'/fill 4 1 1 5 1 15 minecraft:unpowered_repeater 1',
'/fill 6 1 1 6 1 5 minecraft:unpowered_repeater 13 ',
'/setblock 7 1 1 minecraft:unpowered_repeater 13',
'/fill 8 1 2 8 1 6 minecraft:unpowered_repeater 14',
'/setblock 5 1 1 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 0 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 2 1 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"3\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"white\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 3 1 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:block.note.hat ambient @a 0 0 0 1 1 1"}',
'/setblock 5 1 3 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 30 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 7 1 3 minecraft:command_block 1 replace {Command: "/playsound minecraft:entity.wither.spawn ambient @a 0 0 0 1 1 1"}',
'/setblock 7 2 3 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"PVP allowed\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"red\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"bold\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"true\\\\\\\\\\\\\\\"}]"}',
'/setblock 7 3 3 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a subtitle [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Kill them! Kill them with fire!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"white\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 1 5 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 60 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 7 1 5 minecraft:command_block 1 replace {Command: "/worldborder set 200 7200"}',
'/setblock 7 2 5 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:entity.lightning.thunder ambient @a 0 0 0 1 1 1"}',
'/setblock 7 3 5 minecraft:chain_command_block 1 replace {auto:1b,Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"The world border is now shrinking!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"red\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 1 7 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 90 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 1 9 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 120 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 1 11 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 150 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 11 minecraft:unpowered_repeater 13',
'/setblock 7 1 11 minecraft:command_block 1 replace {Command: "/gamerule doDaylightCycle false"}',
'/setblock 7 2 11 minecraft:chain_command_block 1 replace {auto:1b,Command: "/time set 6000"}',
'/setblock 7 3 11 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Shine bright\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"yellow\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"bold\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"true\\\\\\\\\\\\\\\"}]"}',
'/setblock 7 4 11 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a subtitle [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"like a diamond\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"yellow\\\\\\\\\\\\\\\"}]"}',
'/setblock 7 5 11 minecraft:chain_command_block 1 replace {auto:1b,Command: "/effect @a minecraft:glowing 1000000"}',
'/setblock 7 6 11 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:entity.firework.twinkle ambient @a 0 0 0 1 1 1"}',
'/setblock 5 1 13 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 180 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 5 1 15 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 210 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 2 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 15 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 4 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 45 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 6 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 75 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 8 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 105 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 10 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 135 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 12 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 165 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 6 1 14 minecraft:command_block 1 replace {Command: "/tellraw @a [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"This is the 195 min marker!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"gray\\\\\\\\\\\\\\\"}]"}',
'/setblock 8 1 1 minecraft:command_block 1 replace {Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"white\\\\\\\\\\\\\\\"}]"}',
'/setblock 8 2 1 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:block.note.hat ambient @a 0 0 0 1 1 1"}',
'/setblock 8 1 4 minecraft:command_block 1 replace {Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"1\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"white\\\\\\\\\\\\\\\"}]"}',
'/setblock 8 2 4 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:block.note.hat ambient @a 0 0 0 1 1 1"}',
'/setblock 8 1 7 minecraft:command_block 1 replace {Command: "/spreadplayers 0 0 200 1000 true @a"}',
'/setblock 8 2 7 minecraft:chain_command_block 1 replace {auto:1b,Command: "/title @a title [\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Go!\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"color\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"dark_green\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"bold\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"true\\\\\\\\\\\\\\\"}]"}',
'/setblock 8 3 7 minecraft:chain_command_block 1 replace {auto:1b,Command: "/playsound minecraft:block.note.pling ambient @a 0 0 0 1 1 1"}',
'/setblock 1 2 2 minecraft:dropper 2',
'/setblock 1 2 1 minecraft:hopper 0',
'/setblock 1 1 1 minecraft:dropper 1',
'/setblock 2 1 1 minecraft:unpowered_comparator 1',
'/setblock 1 1 4 minecraft:stone',
'/setblock 1 1 5 minecraft:unpowered_comparator 0',
'/setblock 1 1 6 minecraft:hopper 3',
'/setblock 1 1 7 minecraft:hopper 2',
'/setblock 1 1 8 minecraft:unpowered_comparator 2',
'/setblock 1 1 9 minecraft:stone',
'/setblock 1 2 4 minecraft:redstone_wire',
'/setblock 1 2 5 minecraft:sticky_piston 3',
'/setblock 1 2 7 minecraft:redstone_block',
'/setblock 1 2 8 minecraft:sticky_piston 2',
'/setblock 1 2 9 minecraft:redstone_wire',
'/setblock 2 1 15 minecraft:unpowered_repeater 3',
'/fill 1 1 15 1 1 12 minecraft:redstone_wire',
'/setblock 1 1 11 minecraft:stone',
'/setblock 1 2 10 minecraft:stone',
'/setblock 1 3 9 minecraft:stone_slab 8',
'/setblock 1 3 8 minecraft:stone',
'/setblock 1 2 11 minecraft:redstone_wire',
'/setblock 1 3 10 minecraft:redstone_wire',
'/setblock 1 4 9 minecraft:redstone_wire',
'/setblock 1 4 8 minecraft:redstone_wire',
'/setblock 2 1 6 minecraft:stone_slab 8',
'/setblock 2 2 6 minecraft:redstone_wire',
'/fill 2 2 5 2 2 2 minecraft:stone_slab 8',
'/fill 2 3 5 2 3 2 minecraft:redstone_wire',
'/setblock 3 2 6 minecraft:stone',
'/setblock 1 3 4 minecraft:stone',
'/setblock 1 3 2 minecraft:redstone_wire',
'/fill 4 2 12 8 2 15 minecraft:stone_slab 8',
'/fill 5 3 12 8 3 15 minecraft:redstone_wire',
'/setblock 8 3 12 minecraft:stone',
'/fill 6 3 12 7 3 12 minecraft:unpowered_comparator 1',
'/fill 6 3 13 7 3 13 minecraft:unpowered_comparator 3',
'/fill 5 3 14 7 3 15 minecraft:unpowered_repeater 3',
'/setblock 6 3 14 minecraft:command_block 1 replace {Command: "/gamemode 3 @a[score_DEATHS_min=1]"}',
'/setblock 4 3 14 minecraft:command_block 1 replace {Command: "/scoreboard players remove @a[score_DEATHS_min=1] DEATHS 1"}',
'/setblock 6 3 15 minecraft:command_block 1 replace {Command: "/effect @a[score_KILLS_min=1] minecraft:regeneration 8 2"}',
'/setblock 4 3 15 minecraft:command_block 1 replace {Command: "/scoreboard players remove @a[score_KILLS_min=1] KILLS 1"}',
'/setblock 8 3 13 minecraft:unlit_redstone_torch 3',
]

print(createCommandRaw(commands, 20))
